AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: MeetingRoom Management Serverless Architecture Template

Globals:
  Function:
    Timeout: 30
    Runtime: provided.al2023
    Architectures:
      - x86_64
    Environment:
      Variables:
        TABLE_NAME: MeetingRoomSystem
        JWT_SECRET: amangirdharamangirdhar123123

Resources:
  MeetingRoomTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MeetingRoomSystem
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      Tags:
        - Key: Project
          Value: MeetingRoomManagement

  MeetingAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: MeetingAPIGateway
      Description: |
        API Gateway for the application that has authorizer (custom lambda based) and redirects 
        traffic to Lambda invocation
      StageName: Dev
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: JWTAuthorizer
        Authorizers:
          JWTAuthorizer:
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            Identity:
              Headers:
                - Authorization

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: MeetingRoom-Authorizer
      Description: JWT token authorizer
      CodeUri: ./internal/lambda/authorizer
      Handler: bootstrap
      Policies:
        - AWSLambdaBasicExecutionRole

  AuthorizerFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AuthorizerFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MeetingAPIGateway}/*"

  HealthFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: MeetingRoom-Health
      Description: Health check endpoint
      CodeUri: ./internal/lambda/health
      Handler: bootstrap
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Health:
          Type: Api
          Properties:
            RestApiId: !Ref MeetingAPIGateway
            Path: /health
            Method: GET
            Auth:
              Authorizer: NONE

  LoginFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: MeetingRoom-Login
      Description: |
        Login Function lambda
      CodeUri: ./internal/lambda/login
      Handler: bootstrap
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: MeetingRoomSystem
      Events:
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref MeetingAPIGateway
            Path: /login
            Method: POST
            Auth:
              Authorizer: NONE

  GetUserByIdFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: MeetingRoom-GetUserById
      Description: |
        Get User By ID Function lambda
      CodeUri: ./internal/lambda/user/getUserByID
      Handler: bootstrap
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: MeetingRoomSystem
      Events:
        GetUserById:
          Type: Api
          Properties:
            RestApiId: !Ref MeetingAPIGateway
            Path: /api/users/{id}
            Method: GET

  GetAllUsersFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: MeetingRoom-GetAllUsers
      Description: Get all users
      CodeUri: ./internal/lambda/user/getAllUsers
      Handler: bootstrap
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBReadPolicy:
            TableName: MeetingRoomSystem
      Events:
        GetAllUsers:
          Type: Api
          Properties:
            RestApiId: !Ref MeetingAPIGateway
            Path: /api/users
            Method: GET

  RegisterUserFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: MeetingRoom-RegisterUser
      Description: Register a new user
      CodeUri: ./internal/lambda/user/registerUser
      Handler: bootstrap
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: MeetingRoomSystem
      Events:
        RegisterUser:
          Type: Api
          Properties:
            RestApiId: !Ref MeetingAPIGateway
            Path: /api/users/register
            Method: POST
            Auth:
              Authorizer: NONE

  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: MeetingRoom-DeleteUser
      Description: Delete a user by ID
      CodeUri: ./internal/lambda/user/deleteUser
      Handler: bootstrap
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: MeetingRoomSystem
      Events:
        DeleteUser:
          Type: Api
          Properties:
            RestApiId: !Ref MeetingAPIGateway
            Path: /api/users/{id}
            Method: DELETE
